version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-2 --no-include-email)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 895164885144.dkr.ecr.us-east-2.amazonaws.com/team4qbthonservice:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 895164885144.dkr.ecr.us-east-2.amazonaws.com/team4qbthonservice:latest
