FROM maven:3.5-jdk-8 AS build  
COPY src . 
COPY pom.xml .  
RUN mvn -f pom.xml clean package

FROM java:8
COPY --from=build /target/reflect-quiz-0.0.1-SNAPSHOT.jar reflect-quiz-0.0.1-SNAPSHOT.jar
EXPOSE 8080  
ENTRYPOINT ["java","-jar","reflect-quiz-0.0.1-SNAPSHOT.jar"]  